sudo: required
services: 
  - docker
language: generic 

before_install:
  - docker build -t swapnil2911/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swapnil2911/docker-react npm run test